version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.2
  - dependency-name: got
    versions:
    - 11.8.2
  - dependency-name: xstate
    versions:
    - 4.16.0
    - 4.16.2
  - dependency-name: typescript-transform-paths
    versions:
    - 2.2.2
    - 2.2.3
  - dependency-name: handlebars
    versions:
    - 4.7.7
  - dependency-name: yup
    versions:
    - 0.32.9
  - dependency-name: eslint-import-resolver-typescript
    versions:
    - 2.4.0
  - dependency-name: "@xstate/react"
    versions:
    - 1.3.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
  - dependency-name: nodemon
    versions:
    - 2.0.7
  - dependency-name: supertest
    versions:
    - 6.1.3
  - dependency-name: "@types/parcel-bundler"
    versions:
    - 1.12.3
  - dependency-name: "@types/koa"
    versions:
    - 2.11.7
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: koa
    versions:
    - 2.13.1
